## it is a data ingestion related configuration

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/entbappy/branching-tutorial/raw/master/winequality-data.zip
  local_data_file:  artifacts/data_ingestion/data.zip
  unzip_dir:  artifacts/data_ingestion

## now we'll create the configuration parameter and class into the 'entity'

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE:  artifacts/data_validation/status.txt

  # for data vlaidation we'll require schema.yaml 


data_transformation:
  root_dir: artifacts/data_
  data_path:  artifacts/data_ingestion/winequality-red.csv
